export const SEARCHING_TWITTER_USERS = 'SEARCHING_TWITTER_USERS';
export const SEARCHING_TWITTER_USERS_ERROR = 'SEARCHING_TWITTER_USERS_ERROR';
export const SEARCHING_TWITTER_USERS_SUCCESS = 'SEARCHING_TWITTER_USERS_SUCCESS';
export const CLEAR_TWITTER_USERS = 'CLEAR_TWITTER_USERS';
